# this is intended for development use
version: "3"
services:
    database:
        image: circleci/postgres:11-alpine
        ports:
            - "5432:5432"
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tabloid
